/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Project {
  'status' : string,
  'title' : string,
  'description' : string,
  'category' : string,
  'location' : string,
}
export interface _SERVICE {
  'addProject' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllServices' : ActorMethod<[], Array<[string, string]>>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getProjectsByCategory' : ActorMethod<[string], Array<Project>>,
  'initialize' : ActorMethod<[Principal], undefined>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'setAdmin' : ActorMethod<[Principal], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateProject' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];